# Generated by Django 5.1 on 2025-04-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_methods',
            field=models.JSONField(blank=True, default=list, help_text="Firebase authentication methods used by the user (e.g., 'google.com', 'password')"),
        ),
    ]
