# Generated by Django 5.1 on 2025-04-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_auth_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_methods',
            field=models.CharField(max_length=50),
        ),
    ]
