# Generated by Django 5.1 on 2025-04-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_auth_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='research_interests',
        ),
        migrations.AddField(
            model_name='user',
            name='research_interests',
            field=models.ManyToManyField(blank=True, to='authentication.researchinterest'),
        ),
    ]
