# Generated by Django 5.1 on 2025-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_researchinterest_remove_user_research_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_set',
            field=models.BooleanField(default=False),
        ),
    ]
