# Generated by Django 5.1 on 2025-04-29 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default='No description provided', help_text='Room description displayed to users'),
        ),
        migrations.AddField(
            model_name='room',
            name='empty_timeout',
            field=models.IntegerField(default=300, help_text='Seconds to keep room open if empty'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_participants',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(default='Untitled Room', help_text='Room title displayed to users', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.OneToOneField(help_text='Each user can only host one room', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Custom room metadata', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(help_text='LiveKit room ID', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('host', 'Host'), ('moderator', 'Moderator'), ('participant', 'Participant'), ('viewer', 'Viewer')], default='participant', max_length=20)),
                ('can_publish_audio', models.BooleanField(default=True)),
                ('can_publish_video', models.BooleanField(default=True)),
                ('can_publish_data', models.BooleanField(default=True)),
                ('can_subscribe', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='livestream.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
