# Generated by Django 5.1 on 2025-04-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_remove_room_name_room_description_room_empty_timeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(help_text='Room title displayed to users', max_length=255),
        ),
    ]
