# Generated by Django 5.1 on 2025-05-03 07:32

from django.db import migrations

def fix_room_names(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0003_alter_room_description_alter_room_title'),
    ]

    operations = [
        migrations.RunPython(fix_room_names),
    ]