# Generated by Django 5.1 on 2025-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_id'),
        ('livestream', '0007_remove_room_description_remove_room_empty_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='research_interests',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='authentication.researchinterest'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
