# Generated by Django 5.1 on 2025-05-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0008_room_research_interests_alter_room_name'),
        ('papers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('pdf_link', models.URLField(blank=True, max_length=1000)),
                ('extract', models.TextField()),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('original_extract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_instances', to='papers.paperextract')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_extracts', to='livestream.room')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_extracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shared_at'],
            },
        ),
    ]
