# Generated by Django 5.1 on 2025-05-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0009_sharedextract'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedextract',
            name='page_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
