# Generated by Django 5.1 on 2025-05-05 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('publication_info', models.CharField(blank=True, max_length=500)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('pdf_link', models.URLField(blank=True, max_length=1000)),
                ('publication_link', models.URLField(blank=True, max_length=1000)),
                ('extract', models.TextField()),
                ('page_number', models.CharField(blank=True, max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_extracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
